# Generated by Django 4.0 on 2021-12-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='our_goals',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_mission',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='what_we_do',
            field=models.TextField(max_length=1000),
        ),
    ]
