# Generated by Django 4.0 on 2021-12-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertyreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
